Contributing.md beatrix droid
qiskit-community/ecosystem pull request #181
Opened 2022-07-17 14:16 UTC by Beatrix-droid

### Summary

### Details and comments

2022-07-17 14:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/qiskit-community/ecosystem?pullRequest=181) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/ecosystem?pullRequest=181) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/qiskit-community/ecosystem?pullRequest=181) it.</sub>

2022-07-17 14:18 UTC, Beatrix-droid commented
updated the contribution.md file as requested, and created another markdown where the guide on git is, and linked it to the contribution,md file. This makes the contribution.md file less cluttered, as that guide is now gone, but at the same time, users that will need the guidance to make a PR will be pointed to the right resources.

2022-07-18 14:24 UTC, IceKhan13 requested changes
Love it! 

Let's move git guide to docs folder, rename branch and we are ready to merge.

2022-07-18 14:24 UTC, IceKhan13 commented on git-guidance.md
> +      <code> git checkout master </code>   <br/>
Can we rename branches from `master` to `main`?

2022-07-18 15:26 UTC, Beatrix-droid commented on CONTRIBUTING.md
> +and fill in all required details. That's it!
Noted, will make the changes !

2022-07-18 15:46 UTC, closed without merging

2022-07-18 15:48 UTC, Beatrix-droid commented
i have closed this pull request and opened another one with the changes that were requested

2022-07-18 16:17 UTC, IceKhan13 commented
Linking new PR here https://github.com/qiskit-community/ecosystem/pull/182